### ISSUE TITLE
Enabling authentication.enabled              = true  creates installation errors

### ISSUE THREAD

**Issue by gerroon** [simpleinvoices/simpleinvoices#291]
Hi

I am trying to install it on Debian Testing 

10.1.29-MariaDB,
Apache/2.4.33

 
I downloaded the master.zip then downloaded the zend lib into the zend folder. 

I can install and start using SI without the authentication. I see no error, I can open the page click error. But when I enable the authentication to true in the config file this is what I get, this is after installtiong without authentication.

```
Fatal error: Uncaught PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'simpleinvoices.si_user' doesn't exist in /media/var/www/simpleinvoices-master/library/Zend/Db/Statement/Pdo.php:228 Stack trace: #0 /media/var/www/simpleinvoices-master/library/Zend/Db/Statement/Pdo.php(228): PDOStatement->execute(Array) #1 /media/SYSLINX/var/www/simpleinvoices-master/library/Zend/Db/Statement.php(300): Zend_Db_Statement_Pdo->_execute(Array) #2 /media/var/www/simpleinvoices-master/library/Zend/Db/Adapter/Abstract.php(479): Zend_Db_Statement->execute(Array) #3 /media/var/www/simpleinvoices-master/library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query('SELECT `si_user...', Array) #4 /media/var/www/simpleinvoices-master/library/Zend/Db/Adapter/Abstract.php(736): Zend_Db_Adapter_Pdo_Abstract->query(Object(Zend_Db_Select), Array) #5 /media/SYSLINX/var/www/simpleinvoices-master/library/Zend/Auth/Adapter/DbTable.php(480): Zend_Db_Adapter_Abstract->fetchAll in /media/var/www/simpleinvoices-master/library/Zend/Auth/Adapter/DbTable.php on line 490```


Now I clean everything for a fresh install with authentication this time. So I delete the database content, and enable  "authentication.enabled              = true" but this time I can not pass the first page of installation, clicking on the install database does not do anything, and it does not seem to install the database tables. I can solve this issue only if I make  

"authentication.enabled              = true"  line to
" authentication.enabled              = "

I want authentication but I cant go forward, nomatter what I do.

thanks

**Comment by gerroon** [comment]
For test I tryu to copy the lines from the structure.sql and I ran in mysql

```
CREATE TABLE IF NOT EXISTS `si_user` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `email` varchar(255) DEFAULT NULL,
  `role_id` int(11) DEFAULT NULL,
  `domain_id` int(11) NOT NULL DEFAULT '0',
  `password` varchar(64) DEFAULT NULL,
  `enabled` TINYINT(1) DEFAULT 1 NOT NULL,
  `user_id` int(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`domain_id`,`id`),
  UNIQUE KEY `UnqEMailPwd` (`email`, `password`)
) ENGINE=MyISAM;

CREATE TABLE IF NOT EXISTS `si_user_domain` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `name` (`name`)
) ENGINE=MyISAM;

CREATE TABLE IF NOT EXISTS `si_user_role` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `name` (`name`)
) ENGINE=MyISAM;


```


I get this error

```
SQL query:

CREATE TABLE IF NOT EXISTS `si_user` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `email` varchar(255) DEFAULT NULL,
  `role_id` int(11) DEFAULT NULL,
  `domain_id` int(11) NOT NULL DEFAULT '0',
  `password` varchar(64) DEFAULT NULL,
  `enabled` TINYINT(1) DEFAULT 1 NOT NULL,
  `user_id` int(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`domain_id`,`id`),
  UNIQUE KEY `UnqEMailPwd` (`email`, `password`)
) ENGINE=MyISAM

MySQL said: Documentation
#1071 - Specified key was too long; max key length is 1000 bytes
```

**Comment by gerroon** [comment]
I even tried importing the full sql  file with the errors and results above. So the table for the si user seems invalid and fixing that is beyond my understandig of this stuff.


thanks

**Comment by apmuthu** [comment]
Make all VARCHAR (255) fields as VARCHAR(254) and see what gives.
Where compound keys are there, try to make the entire compound key no more than 255/254 in length.
Where multi-byte characters capable databases are used,this may be an issue like `utf8mb4`, etc.

Also, try the table creation without the indices and then manually create the indices one by one, fine-tuning it therefrom.

**Comment by gerroon** [comment]
@apmuthu 

What you are describing is a bit of ahead of me but what I did is this

I opened structure.sql and replaced all varchar(255) with varchar(254) . The I removed all the tables from the simplieinvoice database. Then I imported the new structure.sql but I still get this error with si_user


```
Error

SQL query:

CREATE TABLE IF NOT EXISTS `si_user` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `email` varchar(254) DEFAULT NULL,
  `role_id` int(11) DEFAULT NULL,
  `domain_id` int(11) NOT NULL DEFAULT '0',
  `password` varchar(64) DEFAULT NULL,
  `enabled` TINYINT(1) DEFAULT 1 NOT NULL,
  `user_id` int(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`domain_id`,`id`),
  UNIQUE KEY `UnqEMailPwd` (`email`, `password`)
) ENGINE=MyISAM

MySQL said: Documentation
#1071 - Specified key was too long; max key length is 1000 bytes
```


```
     simpleinvoices 	utf8mb4_general_ci 

   Apache/2.4.33 (Debian)
    Database client version: libmysql - mysqlnd 5.0.12-dev - 20150407 - $Id: 
    PHP extension: mysqliDocumentation curlDocumentation mbstringDocumentation
    PHP version: 7.1.16-1+b2


```

**Comment by apmuthu** [comment]
Change your database to `utf8` with `utf8_unicode_ci` collation.
